export const tags = [
    "все",
    "брендирование",
    "вывеска",
    "фасад",
    "витрина",
    "автомобиль",
  ];
  
  export const works = [
    {
      id: 1,
      title: "Брендирование витрины",
      image: "/works/works1.png",
      tags: ["брендирование", "витрина"],
    },
    {
      id: 2,
      title: "Оформление фасада",
      image: "/works/works2.png",
      tags: ["вывеска", "фасад"],
    },
    {
      id: 3,
      title: "Брендирование авто",
      image: "/works/works3.png",
      tags: ["брендирование", "автомобиль"],
    },
    {
      id: 4,
      title: "Вывеска на фасаде",
      image: "/works/works4.png",
      tags: ["вывеска", "фасад"],
    },
    {
      id: 5,
      title: "Оформление витрины",
      image: "/works/works5.png",
      tags: ["витрина", "брендирование"],
    },
    {
      id: 6,
      title: "Автобрендирование",
      image: "/works/works6.png",
      tags: ["автомобиль", "брендирование"],
    },
    {
      id: 7,
      title: "Фасадная реклама",
      image: "/works/works7.png",
      tags: ["фасад", "наружная реклама"],
    },
    {
      id: 8,
      title: "Световая вывеска",
      image: "/works/works8.png",
      tags: ["вывеска"],
    },
    {
      id: 9,
      title: "Оформление входной группы",
      image: "/works/works9.png",
      tags: ["фасад", "брендирование"],
    },
    {
      id: 10,
      title: "Витрина магазина",
      image: "/works/works10.png",
      tags: ["витрина"],
    },
    {
      id: 11,
      title: "Брендирование грузовика",
      image: "/works/works11.png",
      tags: ["автомобиль", "брендирование"],
    },
    {
      id: 12,
      title: "Фасад кафе",
      image: "/works/works12.png",
      tags: ["фасад"],
    },
    {
      id: 13,
      title: "Яркая вывеска",
      image: "/works/works13.png",
      tags: ["вывеска"],
    },
    {
      id: 14,
      title: "Витрина кафе",
      image: "/works/works14.png",
      tags: ["витрина"],
    },
    {
      id: 15,
      title: "Оклейка автомобиля",
      image: "/works/works15.png",
      tags: ["автомобиль", "брендирование"],
    },
    {
      id: 16,
      title: "Фасад ресторана",
      image: "/works/works16.png",
      tags: ["фасад"],
    },
    {
      id: 17,
      title: "Рекламная вывеска",
      image: "/works/works17.png",
      tags: ["вывеска", "брендирование"],
    },
    {
      id: 18,
      title: "Оформление витрины",
      image: "/works/works18.png",
      tags: ["витрина", "брендирование"],
    },
    {
      id: 19,
      title: "Фирменный стиль авто",
      image: "/works/works19.png",
      tags: ["автомобиль", "брендирование"],
    },
    {
      id: 20,
      title: "Фасад офиса",
      image: "/works/works20.png",
      tags: ["фасад"],
    },
    {
      id: 21,
      title: "Вывеска с подсветкой",
      image: "/works/works21.png",
      tags: ["вывеска"],
    },
    {
      id: 22,
      title: "Рекламная витрина",
      image: "/works/works22.png",
      tags: ["витрина", "брендирование"],
    },
    {
      id: 23,
      title: "Оформление автомобиля",
      image: "/works/works23.png",
      tags: ["автомобиль", "брендирование"],
    },
    {
      id: 24,
      title: "Фасад с вывеской",
      image: "/works/works24.png",
      tags: ["фасад", "вывеска"],
    },
    {
      id: 25,
      title: "Брендинг витрины",
      image: "/works/works25.png",
      tags: ["витрина", "брендирование"],
    },
    {
      id: 26,
      title: "Рекламное оформление авто",
      image: "/works/works26.png",
      tags: ["автомобиль", "брендирование"],
    },
    {
      id: 27,
      title: "Фасадный проект",
      image: "/works/works27.png",
      tags: ["фасад"],
    },
  ];
  